"""
Core backtesting engine package.

Re-exports all public symbols from the engine sub-modules so that
existing code using bare module imports continues to work:

    from enhanced_backtest import ...
    from strike_selector import ...
    from enhanced_multi_strategy import ...
    from query_engine_adapter import ...
"""
